language: ruby
rvm:
- 2.1.2
before_install:
  - gem install 'padrino'
before_script:
  - padrino rake ar:create
  - padrino rake ar:migrate
  - padrino rake seed
script:
  - bundle exec rspec
  - git branch
deploy:
  provider: heroku
  api_key:
    secure: eONgtzPyQBwAOgGwz1P0oRxFdd/zdUWsWnvfcQvBGNn/BM3VMPEMwgaWvnPTPnk47+c63YkowHl8ia3j8hjK2n6QUMDPlSsWnaOM1cD6313mZoszC/siOV+35Et+hxSXLPgFWNYcQY4Cy9NISONhJoLf6sRgZI9dyd956ikLyRk=
  app: ancient-beyond-2712
#  app:
#    master: master
  run:
    - "padrino rake ar:migrate"
    - "padrino rake seed"
    - "padrino s"
 
